"""empty message

Revision ID: 02343423e7c8
Revises: 2ace7544f21e
Create Date: 2020-04-08 14:01:02.753327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02343423e7c8'
down_revision = '2ace7544f21e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'seeking_description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_description', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
